import type { User, Property, RiskReport, RiskItem } from '../types';

// ─── Demo users ──────────────────────────────────────────────────────────────
export const DEMO_USERS: Record<string, User & { password: string }> = {
  'arbeni@demo.ks': {
    id: 'demo-user-buyer',
    email: 'arbeni@demo.ks',
    full_name: 'Arben Gashi',
    role: 'buyer',
    phone: '+383 44 222 333',
    plan: 'free',
    reports_used: 0,
    reports_limit: 999,
    created_at: '2024-01-01T00:00:00Z',
    password: 'password123',
  },
  'admin@prona.ks': {
    id: 'demo-user-admin',
    email: 'admin@prona.ks',
    full_name: 'Admin PronA',
    role: 'admin',
    plan: 'enterprise',
    reports_used: 0,
    reports_limit: 9999,
    created_at: '2024-01-01T00:00:00Z',
    password: 'Admin@2024!',
  },
  'avokati@demo.ks': {
    id: 'demo-user-lawyer',
    email: 'avokati@demo.ks',
    full_name: 'Blerta Krasniqi',
    role: 'lawyer',
    plan: 'professional',
    reports_used: 4,
    reports_limit: 50,
    created_at: '2024-01-01T00:00:00Z',
    password: 'password123',
  },
};

// ─── Demo properties ─────────────────────────────────────────────────────────
export const DEMO_PROPERTIES: Property[] = [
  {
    id: 'demo-prop-1',
    user_id: 'demo-user-buyer',
    title: 'Apartament 2+1 — Rruga Fehmi Agani, Prishtinë',
    address: 'Rruga Fehmi Agani Nr.45, Kati 3, Ap.12, Prishtinë',
    municipality: 'Prishtinë',
    parcel_number: 'P-10234-22',
    property_type: 'apartment',
    area_sqm: 72.5,
    asking_price_eur: 89000,
    seller_name: 'Shpend Morina',
    developer_name: 'Graniti Invest SH.P.K.',
    status: 'complete',
    coordinates_lat: 42.6629,
    coordinates_lng: 21.1655,
    doc_count: 3,
    overall_status: 'green',
    overall_score: 72,
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-03-02T14:00:00Z',
  },
  {
    id: 'demo-prop-2',
    user_id: 'demo-user-buyer',
    title: 'Shtëpi me Parcelë — Fushë Kosovë',
    address: 'Rr. Dardania Nr.8, Fushë Kosovë',
    municipality: 'Fushë Kosovë',
    parcel_number: 'FK-5521-01',
    property_type: 'house',
    area_sqm: 180,
    asking_price_eur: 65000,
    seller_name: 'Agim Ramadani',
    status: 'pending',
    doc_count: 0,
    created_at: '2024-03-10T09:00:00Z',
    updated_at: '2024-03-10T09:00:00Z',
  },
  {
    id: 'demo-prop-3',
    user_id: 'demo-user-buyer',
    title: 'Parcelë Toke — Gjilan',
    address: 'Fshati Bresalc, Gjilan',
    municipality: 'Gjilan',
    parcel_number: 'GJ-8834-15',
    property_type: 'land',
    area_sqm: 500,
    asking_price_eur: 28000,
    seller_name: 'Fatmire Osmani',
    status: 'complete',
    doc_count: 2,
    overall_status: 'red',
    overall_score: 35,
    created_at: '2024-03-15T11:00:00Z',
    updated_at: '2024-03-16T16:00:00Z',
  },
];

// ─── Demo risk items ──────────────────────────────────────────────────────────
const GREEN_ITEMS: RiskItem[] = [
  {
    id: 'ri-1', report_id: 'demo-report-1',
    category: 'permits', severity: 'yellow',
    title: 'Leje Përdorimi (Kolaudim) Mungon',
    description: 'Leja e ndërtimit është prezente dhe e vlefshme, por dokumenti i kolaudimit nuk është ngarkuar.',
    recommendation: 'Kërkoni dokumentin e kolaudimit nga zhvilluesi ose komuna e Prishtinës.',
    is_resolved: false, created_at: '2024-03-02T14:00:00Z',
  },
  {
    id: 'ri-2', report_id: 'demo-report-1',
    category: 'developer', severity: 'yellow',
    title: 'Profil i Kufizuar i Zhvilluesit',
    description: 'Graniti Invest SH.P.K. ka 2 projekte të regjistruara por vetëm 1 të përfunduar.',
    recommendation: 'Kontrolloni historikun e plotë të kompanisë në: arbk.rks-gov.net',
    is_resolved: false, created_at: '2024-03-02T14:00:00Z',
  },
  {
    id: 'ri-3', report_id: 'demo-report-1',
    category: 'compliance', severity: 'info',
    title: 'Verifikim Final i Rekomanduar',
    description: 'Gjithçka duket në rregull. Rekomandohet vizita fizike në AKK.',
    recommendation: 'Vizitoni AKK online ose zyren komunale para nënshkrimit.',
    is_resolved: false, created_at: '2024-03-02T14:00:00Z',
  },
];

const RED_ITEMS: RiskItem[] = [
  {
    id: 'ri-4', report_id: 'demo-report-3',
    category: 'permits', severity: 'red',
    title: 'Leje Ndërtimi Mungon Plotësisht',
    description: 'Nuk ka asnjë leje ndërtimi të ngarkuar. Toka mund të jetë pa leje ndërtimi.',
    recommendation: 'MOS procedoni me blerjen pa siguruar lejen e ndërtimit nga komuna e Gjilanit.',
    is_resolved: false, created_at: '2024-03-16T16:00:00Z',
  },
  {
    id: 'ri-5', report_id: 'demo-report-3',
    category: 'ownership', severity: 'red',
    title: 'Mospërputhje në Numrin e Parcelës',
    description: 'Numri i parcelës nuk përputhet mes dokumenteve. Rrezik i lartë mashtrimesh.',
    recommendation: 'Verifikoni numrin e saktë direkt me AKK.',
    is_resolved: false, created_at: '2024-03-16T16:00:00Z',
  },
  {
    id: 'ri-6', report_id: 'demo-report-3',
    category: 'cadastral', severity: 'yellow',
    title: 'Ekstrakt Kadastral i Vjetëruar',
    description: 'Ekstrakt kadastral i ngarkuar është mbi 6 muaj i vjetër.',
    recommendation: 'Kërkoni ekstrakt kadastral të ri (jo më të vjetër se 30 ditë).',
    is_resolved: false, created_at: '2024-03-16T16:00:00Z',
  },
];

// ─── Demo reports ─────────────────────────────────────────────────────────────
export const DEMO_REPORTS: Record<string, RiskReport> = {
  'demo-prop-1': {
    id: 'demo-report-1',
    property_id: 'demo-prop-1',
    overall_score: 72,
    overall_status: 'green',
    cadastral_status: 'green',
    permit_status: 'yellow',
    ownership_status: 'green',
    mortgage_status: 'green',
    developer_status: 'yellow',
    ai_summary: 'Dokumentet kryesore janë prezente dhe konsistente. Ekstrakt kadastral konfirmon pronësinë. Leja e ndërtimit është e vlefshme por mungon leja e përdorimit (kolaudimi). Zhvilluesi ka projekte të suksesshme në Prishtinë.',
    questions_for_seller: [
      'A ka leje përdorimi (kolaudim) ky apartament?',
      'A janë paguar të gjitha faturat e komunaleve?',
      'A ka ndonjë modifikim pas lejes së ndërtimit?',
    ],
    questions_for_notary: [
      'A konfirmon ekstrakt kadastral numrin e parcelës P-10234-22?',
      'A ka barrë ose hipotekë aktive mbi këtë pronë?',
      'A ka procedura trashëgimie të hapur?',
    ],
    missing_documents: ['Leje Përdorimi (Kolaudim)'],
    disclaimer: 'PARALAJMËRIM LIGJOR: Ky raport është informativ dhe nuk përbën këshillë ligjore. Konsultohuni me noter ose avokat të licencuar para çdo transaksioni.',
    version: 1,
    risk_items: GREEN_ITEMS,
    created_at: '2024-03-02T14:00:00Z',
    updated_at: '2024-03-02T14:00:00Z',
  },
  'demo-prop-3': {
    id: 'demo-report-3',
    property_id: 'demo-prop-3',
    overall_score: 35,
    overall_status: 'red',
    cadastral_status: 'yellow',
    permit_status: 'red',
    ownership_status: 'red',
    mortgage_status: 'yellow',
    developer_status: 'green',
    ai_summary: 'Mungojnë dokumente kritike. Nuk ka leje ndërtimi dhe kontrata e pronësisë ka mospërputhje me numrin e parcelës. Kërkohet verifikim urgjent para çdo pagese.',
    questions_for_seller: [
      'Cili është numri i saktë i parcelës sipas AKK?',
      'A ka ndonjë mosmarrëveshje mbi kufijtë e parcelës?',
      'A ekziston ndonjë vendim gjyqësor për këtë tokë?',
      'A janë paguar të gjitha taksat e pronës?',
    ],
    questions_for_notary: [
      'A konfirmon dokumentacioni se shitësi është pronari i vetëm?',
      'A ka vendime gjyqësore mbi këtë parcelë?',
      'A ka procedura eksproprijimi nga shteti?',
    ],
    missing_documents: ['Leje Ndërtimi', 'Kontratë Pronësie', 'Certifikatë Hipoteke'],
    disclaimer: 'PARALAJMËRIM LIGJOR: Ky raport është informativ dhe nuk përbën këshillë ligjore. Konsultohuni me noter ose avokat të licencuar para çdo transaksioni.',
    version: 1,
    risk_items: RED_ITEMS,
    created_at: '2024-03-16T16:00:00Z',
    updated_at: '2024-03-16T16:00:00Z',
  },
};

export const DEMO_ADMIN_STATS = {
  totals: { users: 4, properties: 3, reports: 2, documents: 5 },
  recent_activity: [
    { full_name: 'Arben Gashi', email: 'arbeni@demo.ks', property_count: 3, last_activity: '2024-03-16T16:00:00Z' },
    { full_name: 'Blerta Krasniqi', email: 'avokati@demo.ks', property_count: 0, last_activity: null },
  ],
  risk_distribution: [
    { overall_status: 'green', count: '1' },
    { overall_status: 'red', count: '1' },
  ],
  daily_signups: [
    { date: '2024-03-01', count: '2' },
    { date: '2024-03-10', count: '1' },
    { date: '2024-03-15', count: '1' },
  ],
};
